experiment_name: titanic_gbm_benchmarking_run
hyperopt: false
profiler:
  enable: false
export:
  export_artifacts: false
experiments:
  - dataset_name: titanic
    config_path: titanic_gbm.yaml
  - dataset_name: titanic
    config_path: titanic_ecd.yaml
