# Apply to all files without committing:
#   pre-commit run --all-files
# Apply to changed files:
#   pre-commit run
# Update this file:
#   pre-commit autoupdate

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
