defaults:
  number:
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
input_features:
- name: age
  type: number
- name: workclass
  type: category
- name: fnlwgt
  type: number
- name: education
  type: category
- name: education-num
  type: number
- name: marital-status
  type: category
- name: occupation
  type: category
- name: relationship
  type: category
- name: race
  type: category
- name: sex
  type: category
- name: capital-gain
  type: number
- name: capital-loss
  type: number
- name: hours-per-week
  type: number
- name: native-country
  type: category
output_features:
- name: income
  type: category
trainer:
  bagging_fraction: 0.5427653655234915
  bagging_freq: 9
  early_stop: 7
  feature_fraction: 0.3919861080620951
  lambda_l1: 1.9457075261981014e-05
  lambda_l2: 3.3183332312056295e-08
  learning_rate: 0.001874613291203257
  max_bin: 66912
  max_depth: 85
  min_data_in_leaf: 100
  min_gain_to_split: 0.07762621116544131
  min_sum_hessian_in_leaf: 3
  num_boost_round: 5515
  num_leaves: 183
type: gbm
