defaults:
  number:
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: null
input_features:
- encoder: sparse
  name: cap-shape
  type: category
- encoder: sparse
  name: cap-surface
  type: category
- encoder: sparse
  name: cap-color
  type: category
- encoder: sparse
  name: bruises?
  type: category
- encoder: sparse
  name: odor
  type: category
- encoder: sparse
  name: gill-attachment
  type: category
- encoder: sparse
  name: gill-spacing
  type: category
- encoder: sparse
  name: gill-size
  type: category
- encoder: sparse
  name: gill-color
  type: category
- encoder: sparse
  name: stalk-shape
  type: category
- encoder: sparse
  name: stalk-root
  type: category
- encoder: sparse
  name: stalk-surface-above-ring
  type: category
- encoder: sparse
  name: stalk-surface-below-ring
  type: category
- encoder: sparse
  name: stalk-color-above-ring
  type: category
- encoder: sparse
  name: stalk-color-below-ring
  type: category
- encoder: sparse
  name: veil-type
  type: category
- encoder: sparse
  name: veil-color
  type: category
- encoder: sparse
  name: ring-number
  type: category
- encoder: sparse
  name: ring-type
  type: category
- encoder: sparse
  name: spore-print-color
  type: category
- encoder: sparse
  name: population
  type: category
- encoder: sparse
  name: habitat
  type: category
output_features:
- encoder: sparse
  name: class
  type: category
trainer:
  bagging_fraction: 0.3185750525468673
  bagging_freq: 6
  early_stop: 7
  feature_fraction: 0.22909622450175604
  lambda_l1: 0.0035948705247451397
  lambda_l2: 8.029383793535553
  learning_rate: 0.00231307551704296
  max_bin: 67094
  max_depth: 134
  min_data_in_leaf: 142
  min_gain_to_split: 0.029777604793146503
  min_sum_hessian_in_leaf: 7
  num_boost_round: 9428
  num_leaves: 58
type: gbm
