input_features:
  - column: lp
    name: lp
    type: number
  - column: v
    name: v
    type: number
  - column: gtt
    name: gtt
    type: number
  - column: gtn
    name: gtn
    type: number
  - column: ggn
    name: ggn
    type: number
  - column: ts
    name: ts
    type: number
  - column: tp
    name: tp
    type: number
  - column: t48
    name: t48
    type: number
  - column: t1
    name: t1
    type: category
  - column: t2
    name: t2
    type: number
  - column: p48
    name: p48
    type: number
  - column: p1
    name: p1
    type: number
  - column: p2
    name: p2
    type: number
  - column: pexh
    name: pexh
    type: number
  - column: tic
    name: tic
    type: number
  - column: mf
    name: mf
    type: number
  - column: gttdsc
    name: gttdsc
    type: number
output_features:
  - column: gtcdsc
    name: gtcdsc
    type: number
preprocessing:
  split:
    type: fixed
