defaults:
  number:
    preprocessing:
      missing_value_strategy: fill_with_const
      normalization: zscore
input_features:
- column: feature1
  name: feature1
  type: number
- column: feature2
  name: feature2
  type: number
- column: feature3
  name: feature3
  type: number
- column: feature4
  name: feature4
  type: number
- column: feature5
  name: feature5
  type: number
- column: feature6
  name: feature6
  type: number
- column: feature7
  name: feature7
  type: number
- column: feature8
  name: feature8
  type: number
- column: feature9
  name: feature9
  type: number
- column: feature10
  name: feature10
  type: number
- column: feature11
  name: feature11
  type: number
- column: feature12
  name: feature12
  type: number
- column: feature13
  name: feature13
  type: number
- column: feature14
  name: feature14
  type: number
- column: feature15
  name: feature15
  type: number
- column: feature16
  name: feature16
  type: number
- column: feature17
  name: feature17
  type: number
- column: feature18
  name: feature18
  type: number
- column: feature19
  name: feature19
  type: number
- column: feature20
  name: feature20
  type: number
- column: feature21
  name: feature21
  type: number
output_features:
- column: target
  name: target
  type: binary
trainer:
  bagging_fraction: 0.02949728556936026
  bagging_freq: 9
  early_stop: 7
  feature_fraction: 0.6747856593011485
  lambda_l1: 0.0048598244894892464
  lambda_l2: 1.3062517657560707e-05
  learning_rate: 0.09939660567895521
  max_bin: 12367
  max_depth: 236
  min_data_in_leaf: 195
  min_gain_to_split: 0.18993841755954655
  min_sum_hessian_in_leaf: 8
  num_boost_round: 4864
  num_leaves: 178
type: gbm
