output_features:
  - name: target
    type: category
input_features:
  - name: feat_1
    type: category
  - name: feat_2
    type: category
  - name: feat_3
    type: category
  - name: feat_4
    type: category
  - name: feat_5
    type: category
  - name: feat_6
    type: category
  - name: feat_7
    type: category
  - name: feat_8
    type: category
  - name: feat_9
    type: category
  - name: feat_10
    type: category
  - name: feat_11
    type: category
  - name: feat_12
    type: category
  - name: feat_13
    type: category
  - name: feat_14
    type: category
  - name: feat_15
    type: category
  - name: feat_16
    type: category
  - name: feat_17
    type: category
  - name: feat_18
    type: category
  - name: feat_19
    type: category
  - name: feat_20
    type: category
  - name: feat_21
    type: category
  - name: feat_22
    type: category
  - name: feat_23
    type: category
  - name: feat_24
    type: category
  - name: feat_25
    type: category
  - name: feat_26
    type: category
  - name: feat_27
    type: category
  - name: feat_28
    type: category
  - name: feat_29
    type: category
  - name: feat_30
    type: category
  - name: feat_31
    type: category
  - name: feat_32
    type: category
  - name: feat_33
    type: category
  - name: feat_34
    type: category
  - name: feat_35
    type: category
  - name: feat_36
    type: category
  - name: feat_37
    type: category
  - name: feat_38
    type: category
  - name: feat_39
    type: category
  - name: feat_40
    type: category
  - name: feat_41
    type: category
  - name: feat_42
    type: category
  - name: feat_43
    type: category
  - name: feat_44
    type: category
  - name: feat_45
    type: category
  - name: feat_46
    type: category
  - name: feat_47
    type: category
  - name: feat_48
    type: category
  - name: feat_49
    type: category
  - name: feat_50
    type: category
  - name: feat_51
    type: category
  - name: feat_52
    type: category
  - name: feat_53
    type: category
  - name: feat_54
    type: category
  - name: feat_55
    type: category
  - name: feat_56
    type: category
  - name: feat_57
    type: category
  - name: feat_58
    type: category
  - name: feat_59
    type: category
  - name: feat_60
    type: category
  - name: feat_61
    type: category
  - name: feat_62
    type: category
  - name: feat_63
    type: category
  - name: feat_64
    type: category
  - name: feat_65
    type: category
  - name: feat_66
    type: category
  - name: feat_67
    type: category
  - name: feat_68
    type: category
  - name: feat_69
    type: category
  - name: feat_70
    type: category
  - name: feat_71
    type: category
  - name: feat_72
    type: category
  - name: feat_73
    type: category
  - name: feat_74
    type: category
  - name: feat_75
    type: category
  - name: feat_76
    type: category
  - name: feat_77
    type: category
  - name: feat_78
    type: category
  - name: feat_79
    type: category
  - name: feat_80
    type: category
  - name: feat_81
    type: category
  - name: feat_82
    type: category
  - name: feat_83
    type: category
  - name: feat_84
    type: category
  - name: feat_85
    type: category
  - name: feat_86
    type: category
  - name: feat_87
    type: category
  - name: feat_88
    type: category
  - name: feat_89
    type: category
  - name: feat_90
    type: category
  - name: feat_91
    type: category
  - name: feat_92
    type: category
  - name: feat_93
    type: category
combiner:
  type: tabnet
  size: 128
  output_size: 128
  sparsity: 0
  bn_momentum: 0.8
  num_steps: 3
  relaxation_factor: 1
  bn_virtual_bs: 512
trainer:
  batch_size: 256
  eval_batch_size: 0
  epochs: 300
  early_stop: 30
  learning_rate: 0.005
  optimizer:
    type: adam
  decay: true
  decay_steps: 20000
  decay_rate: 0.4
  validation_metric: accuracy
