defaults:
  number:
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
input_features:
- name: F1
  type: number
- name: F2
  type: number
- name: F3
  type: number
- name: F4
  type: number
- name: F5
  type: number
- name: F6
  type: number
- name: F7
  type: number
- name: F8
  type: number
- name: F9
  type: number
- name: F1
  type: number
output_features:
- name: RMSD
  type: number
trainer:
  bagging_fraction: 0.597708911965363
  bagging_freq: 0
  early_stop: 7
  feature_fraction: 0.742028259091312
  lambda_l1: 0.6238254864134898
  lambda_l2: 3.913684846923848e-06
  learning_rate: 0.023986973670470115
  max_bin: 89776
  max_depth: 477
  min_data_in_leaf: 111
  min_gain_to_split: 0.06708256033463586
  min_sum_hessian_in_leaf: 5
  num_boost_round: 3911
  num_leaves: 314
type: gbm
