defaults:
  number:
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
input_features:
- column: position_1
  name: position_1
  type: number
- column: position_2
  name: position_2
  type: number
- column: position_3
  name: position_3
  type: number
- column: position_4
  name: position_4
  type: number
- column: position_5
  name: position_5
  type: number
- column: position_6
  name: position_6
  type: number
- column: position_7
  name: position_7
  type: number
- column: velocity_1
  name: velocity_1
  type: number
- column: velocity_2
  name: velocity_2
  type: number
- column: velocity_3
  name: velocity_3
  type: number
- column: velocity_4
  name: velocity_4
  type: number
- column: velocity_5
  name: velocity_5
  type: number
- column: velocity_6
  name: velocity_6
  type: number
- column: velocity_7
  name: velocity_7
  type: number
- column: acceleration_1
  name: acceleration_1
  type: number
- column: acceleration_2
  name: acceleration_2
  type: number
- column: acceleration_3
  name: acceleration_3
  type: number
- column: acceleration_4
  name: acceleration_4
  type: number
- column: acceleration_5
  name: acceleration_5
  type: number
- column: acceleration_6
  name: acceleration_6
  type: number
- column: acceleration_7
  name: acceleration_7
  type: number
- column: torque_2
  name: torque_2
  type: number
- column: torque_3
  name: torque_3
  type: number
- column: torque_4
  name: torque_4
  type: number
- column: torque_5
  name: torque_5
  type: number
- column: torque_6
  name: torque_6
  type: number
- column: torque_7
  name: torque_7
  type: number
output_features:
- column: torque_1
  name: torque_1
  type: number
trainer:
  bagging_fraction: 0.9003624837953828
  bagging_freq: 6
  early_stop: 7
  feature_fraction: 0.3431442435276645
  lambda_l1: 0.0025617456949545967
  lambda_l2: 0.13764427150195657
  learning_rate: 0.0015118345699210436
  max_bin: 75682
  max_depth: 295
  min_data_in_leaf: 124
  min_gain_to_split: 0.06232840547324209
  min_sum_hessian_in_leaf: 6
  num_boost_round: 7833
  num_leaves: 451
type: gbm
