hyperopt:
  # goal: maximize
  parameters:
    training.learning_rate:
      type: float
      lower: 0.00002
      upper: 0.00005
      space: loguniform
    training.batch_size:
      space: choice
      categories: [8, 16, 32, 64, 128]
