input_features:
  - name: Elevation
    type: numerical
  - name: Aspect
    type: numerical
  - name: Slope
    type: numerical
  - name: Horizontal_Distance_To_Hydrology
    type: numerical
  - name: Vertical_Distance_To_Hydrology
    type: numerical
  - name: Horizontal_Distance_To_Roadways
    type: numerical
  - name: Hillshade_9am
    type: numerical
  - name: Hillshade_Noon
    type: numerical
  - name: Hillshade_3pm
    type: numerical
  - name: Horizontal_Distance_To_Fire_Points
    type: numerical
  - name: Wilderness_Area
    type: category
  - name: Soil_Type
    type: category
output_features:
  - name: Cover_Type
    type: category
training:
  epochs: 20
