version: 1.0
name: alpaca
download_urls: https://github.com/tatsu-lab/stanford_alpaca/blob/main/alpaca_data.json
loader: json.JsonLoader
description: |
  Stanford Alpaca instruction-tuning dataset (https://github.com/tatsu-lab/stanford_alpaca) for LLM fine-tuning.
columns:
  - name: instruction
    type: text
  - name: input
    type: text
output_features:
  - name: output
    type: text
