version: 1.0
name: amazon_employee_access_challenge
kaggle_competition: amazon-employee-access-challenge
archive_filenames: amazon-employee-access-challenge.zip
train_filenames: train.csv
test_filenames: test.csv
