version: 1.0
name: av_mnist
download_urls:
  - https://http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
  - https://http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
  - https://http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
  - https://http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
archive_filenames:
  - train-images-idx3-ubyte.gz
  - train-labels-idx1-ubyte.gz
  - t10k-images-idx3-ubyte.gz
  - t10k-labels-idx1-ubyte.gz
train_filenames:
  - train-images-idx3-ubyte
  - train-labels-idx1-ubyte
test_filenames:
  - t10k-images-idx3-ubyte
  - t10k-labels-idx1-ubyte
sha256:
  house-prices-advanced-regression-techniques.zip: 65f769a9157a2581671957ed08da8a8162d53e67b4e9970ee856b634deb11d9f
description: |
  This file is used to process the original mnist and generate the part of the image of the audio-visual mnist dataset.