version: 1.0
name: avmnist
download_urls:
  - http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
sha256:
  t10k-images-idx3-ubyte.gz: 8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6
  train-images-idx3-ubyte.gz: 440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609
  train-labels-idx1-ubyte.gz: 3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c
  t10k-labels-idx1-ubyte.gz: f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6
preserve_paths:
  - training
  - testing
loader: av_mnist.AVMNISTLoader
file_names:
  train_data: train-images-idx3-ubyte.gz
  train_labels: train-labels-idx1-ubyte.gz
  test_data: t10k-images-idx3-ubyte.gz
  test_labels: t10k-labels-idx1-ubyte.gz

description: |
  This file is used to process the original mnist and generate the part of the image of the audio-visual mnist dataset.