version: 1.0
name: hugging_face_t2t_gen
huggingface_dataset_id: placeholder
huggingface_subsample: placeholder
loader: hugging_face.HFText2TextGenerationLoader
description: |
  Hugging Face Text2Text Generation Datasets
