version: 1.0
name: protein
download_urls: http://archive.ics.uci.edu/ml/machine-learning-databases/00265/casp.csv
sha256:
  casp.csv: 4277cfcb4e91a181746cbc654f001b57951c9e6a80f4f795fdb5c807e0848f40
description: |
  physicochemical properties of protein tertiary structure data set.
  https://archive.ics.uci.edu/ml/datasets/physicochemical+properties+of+protein+tertiary+structure
output_features:
  - name: rmsd
    type: number
