version: 1.0
name: sarcastic_headlines
train_filenames: Sarcasm_Headlines_Dataset.json
archive_filenames: news-headlines-dataset-for-sarcasm-detection.zip
kaggle_dataset_id: rmisra/news-headlines-dataset-for-sarcasm-detection
description: A dataset to determine if a news headline is sarcastic or serious.
loader: sarcastic_headlines.SarcasticHeadlinesLoader
