version: 1.0
name: spam_assassin
download_urls:
  - https://spamassassin.apache.org/old/publiccorpus/20030228_easy_ham.tar.bz2
  - https://spamassassin.apache.org/old/publiccorpus/20030228_hard_ham.tar.bz2
  - https://spamassassin.apache.org/old/publiccorpus/20030228_spam.tar.bz2
  - https://spamassassin.apache.org/old/publiccorpus/20030228_easy_ham_2.tar.bz2
  - https://spamassassin.apache.org/old/publiccorpus/20050311_spam_2.tar.bz2
dataset_filenames:
  - 20030228_easy_ham/**/*.eml
description: |
  6048 emails, grouped into three categories: easy_ham, spam, hard_ham
