version: 1.0
name: twitter_bots
kaggle_dataset_id: danieltreiman/twitter-human-bots-dataset
archive_filenames: twitter-human-bots-dataset.zip
dataset_filenames: twitter_human_bots_dataset.csv
preserve_paths:
  - profile_images
  - profile_background_images
description: |
  An dataset for Twitter Bot account detection
