version: 1.0
name: wine_reviews
download_urls:
  - https://automl-mm-bench.s3.amazonaws.com/wine_reviews/train.csv
  - https://automl-mm-bench.s3.amazonaws.com/wine_reviews/test.csv
train_filenames: train.csv
test_filenames: test.csv
description: |
  Wine Reviews
  130k wine reviews with variety, location, winery, price, and description
  https://www.kaggle.com/datasets/zynicide/wine-reviews
