version: 1.0
name: yosemite
download_urls:
  - https://raw.githubusercontent.com/ourownstory/neuralprophet-data/main/datasets_raw/yosemite_temps.csv
description: |
    Yosemite temperatures dataset.
    As found in https://github.com/ourownstory/neural_prophet.
