training:
  batch_size: auto #256
  learning_rate: auto #.001
  # validation_metric: accuracy

hyperopt:
  sampler:
    type: ray
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
    num_samples: 20

  executor:
    type: ray
    time_budget_s: 6000
