combiner:
  type: concat
  num_fc_layers: 3
  fc_size: 128
  dropout: 0.1

training:
  batch_size: 256
  learning_rate: .001
  # validation_metric: accuracy
  tune_batch_size:
    type: bin_search
    substitute_with_max: True

hyperopt:
  # goal: maximize
  parameters:
    combiner.num_fc_layers:
      space: randint
      type: int
      lower: 1
      upper: 8
    combiner.fc_size:
      space: choice
      categories: [128, 256, 512, 1024]
    combiner.dropout:
      space: uniform
      type: float
      lower: 0.0
      upper: 0.1
    training.learning_rate:
      space: loguniform
      lower: 0.0001
      upper: 0.01
    training.batch_size:
      space: choice
      categories: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

  sampler:
    type: ray
    scheduler:
      type: pbt
      time_attr: training_iteration
      perturbation_interval: 10
    num_samples: 40 # TODO (ASN): calibrate perturbation interval

  executor:
    type: ray
    time_budget_s: 6000
