combiner:
  type: transformer
  num_layers: 6
  num_heads: 8
  hidden_size: 32
  dropout: 0.1
  fc_dropout: 0.2
  num_fc_layers: 1

training:
  batch_size: 256
  learning_rate: 0.0001
  validation_metric: accuracy
  tune_batch_size:
    type: bin_search
    substitute_with_max: True

hyperopt:
  goal: maximize
  parameters:
    training.learning_rate:
      space: loguniform
      lower: 0.00001
      upper: 0.01
    training.batch_size:
      space: choice
      categories: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
    combiner.num_heads:
      space: choice
      categories: [2, 4, 8]
    combiner.dropout:
      space: uniform
      type: float
      lower: 0.1
      upper: 0.5
    combiner.num_layers:
      space: randint
      type: int
      lower: 1
      upper: 6
    combiner.num_fc_layers:
      space: choice
      categories: [1, 2]
    combiner.fc_dropout:
      space: uniform
      type: float
      lower: 0.1
      upper: 0.5

  sampler:
    type: ray
    scheduler:
      type: pbt
      time_attr: timesteps_total
      perturbation_interval: 10 # TODO (ASN): calibrate perturbation interval
    num_samples: 40

  executor:
    type: ray
    time_budget_s: 6000
