input_features:
  - name: Seattle
    type: timeseries
    preprocessing:
      window_size: 10
output_features:
  - name: Seattle_next
    type: timeseries
    column: Seattle
    preprocessing:
      horizon: 2
    decoder:
      activation: tanh
      multiplier: 100
preprocessing:
  split:
    type: datetime
    column: datetime
