input_features:
  - name: Seattle
    type: timeseries
    preprocessing:
      window_size: 10
    encoder:
      type: dense
output_features:
  - name: Seattle_next
    type: timeseries
    column: Seattle
    preprocessing:
      horizon: 2
preprocessing:
  split:
    type: datetime
    column: datetime
