name: pytest

on:
  push:
    branches: ["master", "release-*"]
  pull_request:
    branches: ["master", "release-*"]

# we want an ongoing run of this workflow to be canceled by a later commit
# so that there is only one concurrent run of this workflow for each branch
concurrency:
  group: test-getting-started-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test Getting Started
    runs-on: ubuntu-latest

    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Linux
        if: runner.os == 'linux'
        run: |
          sudo apt-get install -y cmake libsndfile1

      - name: Setup macOS
        if: runner.os == 'macOS'
        run: |
          brew install libuv

      - name: Install dependencies
        run: |
          python --version
          pip --version
          python -m pip install -U pip
          pip install '.'
        shell: bash

      - name: Tests
        run: |
          sh ./examples/getting_started/command_line.sh
        shell: bash

      - name: Upload Unit Test Results
        if: ${{ always() && !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }} ${{ matrix.test-markers }})
          path: pytest.xml
